spring:
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:htp://localhost:8888

  application:
    name: item-service
  profiles:
    active: dev
server:
  port: 8085
management:
  endpoints:
    web:
      exposure:
        include: '*'
